/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PillerBabysitteraKata;

import org.junit.Test;
import static org.junit.Assert.*;

public class BabysitterTest {
    
	@Test
	public void validateWithinHoursOfAvailability () {
		Babysitter A = new Babysitter();
		A.setStartTime(17);
		A.setEndTime(28);
		boolean expected = true;
		boolean actual = A.validateWithinHoursOfAvailability(17, 28);
		assertEquals(expected, actual);
	}
	
	@Test
	public void familyTotalBasedOnServiceNeeds() {
		Babysitter A = new Babysitter();
		A.setStartTime(20);
		A.setEndTime(26);
		A.setEarlyPay(15);
		A.setLatePay(20);
		int expected = 105;
		int actual = A.familyTotalBasedOnServiceNeeds();
		assertEquals(expected, actual);
	}
}
